### ISSUE TITLE
Function to hide or customize time / date dump because of long paths or classes names

### ISSUE THREAD

**Issue by enricoangelon** [SebiSebi/friendlylog#8]
I was wondering if would be possible to add a function to hide or maybe to customize the formatter because for long paths, the log looks horrible
example:
[11-Feb-20 15:43:46.291 in C:/Users/xxx/xxxxxxxxxxxxxxx/xxxxxxxx/src/xxxxxxxxxxxx/xxxxx.py - init:  18] Log here, after 3000 lines of path

**Comment by gmuraru** [comment]
I can take it @SebiSebi

**Comment by SebiSebi** [comment]
Thank you, @gmuraru!
